version: '3.8'

services:
  react-app:
    build:
      context: .
    ports:
      - '3000:3000'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data:  
